### ISSUE TITLE
Use https with username and password to connect to ELK

### ISSUE THREAD

**Issue by Vitalii-Syniahovskyi-AAA** [codinux-gmbh/quarkus-elasticsearch-logger#1]
Hi.
I want to use this logger with elastic, but I didn't find where to define username and password to connect to elastic.
Is that option available or not?

**Comment by codinux-gmbh** [comment]
Currently not but it shouldn't be that hard to implement.

Give me a few days - I currently got a lot of work to do - then I will do it.

**Comment by Vitalii-Syniahovskyi-AAA** [comment]
Thanks a lot.
I'll wait

**Comment by codinux-gmbh** [comment]
Just pushed `2.2.0-SNAPSHOT` version. Could you courteously test it? As I got for different companies access to 5 Elasticsearch clusters, but they are all Kubernetes internal and therefore without authentication, so there's no way for me to test it.

Add this to your Quarkus `application.properties`:
```
quarkus.log.elasticsearch.username=<your_username>
quarkus.log.elasticsearch.password=<your_password>
```

And in your `build.gradle`:
```
    repositories {
        maven { url = "https://s01.oss.sonatype.org/content/repositories/snapshots" }
    }

    dependencies {
        implementation "net.codinux.log:quarkus-elasticsearch-logger:2.2.0-SNAPSHOT"
    }
```

or respectively in your `pox.xml`:
```
	<dependencies>
		<dependency>
			<groupId>net.codinux.log</groupId>
			<artifactId>quarkus-elasticsearch-logger</artifactId>
			<version>2.2.0-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>Maven Central Snapshots</id>
			<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```

**Comment by miramax777** [comment]
Hi.
I try to use this plugin with last quarkus and with this new authorization feature.

I use java 16, my build.gradle is 

`plugins {
    id 'java'
    id 'io.quarkus'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = "https://s01.oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-hibernate-validator:2.7.2.Final'
    implementation 'io.quarkus:quarkus-config-yaml:2.7.2.Final'
    implementation 'io.quarkus:quarkus-smallrye-openapi:2.7.2.Final'
    implementation 'io.quarkus:quarkus-rest-client:2.7.2.Final'
    implementation 'io.quarkus:quarkus-rest-client-jackson:2.7.2.Final'
    implementation 'io.quarkus:quarkus-resteasy:2.7.2.Final'
    implementation 'io.quarkus:quarkus-resteasy-jackson:2.7.2.Final'
    implementation 'io.quarkiverse.rabbitmqclient:quarkus-rabbitmq-client:0.4.2.Final'
    implementation 'io.quarkus:quarkus-arc:2.7.2.Final'
    implementation 'io.quarkus:quarkus-redis-client:2.7.2.Final'
    implementation 'io.quarkus:quarkus-mailer:2.7.2.Final'
    implementation 'io.quarkus:quarkus-qute:2.7.2.Final'
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    implementation 'com.google.protobuf:protobuf-java-util:3.19.4'
    implementation 'io.quarkus:quarkus-oidc:2.7.1.Final'
    implementation 'com.global_contracts:global_contracts:3.2-java'
    implementation 'org.json:json:20180813'
    implementation 'org.bouncycastle:bcpkix-jdk15on:1.47'
    implementation 'net.codinux.log:quarkus-elasticsearch-logger:2.2.0-SNAPSHOT'
    implementation group: 'commons-logging', name: 'commons-logging', version: '1.2'
    testImplementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.17.2'
    testImplementation 'io.quarkus:quarkus-junit5:2.7.2.Final'
    testImplementation 'io.rest-assured:rest-assured:4.5.1'
    testImplementation 'org.testcontainers:junit-jupiter:1.16.3'
    testImplementation 'io.quarkus:quarkus-junit5-mockito:2.7.1.Final'

}

group 'com.test'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}`

And i build the native image using command : 
`./gradlew quarkusBuild -Dquarkus.profile=dev -Dquarkus.package.type=native -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.2.0-java16 -Dquarkus.native.report-errors-at-runtime=true -Dnative-image.xmx=3g -Dquarkus.debug.reflection=true
`
And native image build fine.

But when I run it after, I receive exception:
[WARN] BasicAuthCache - Unexpected error while de-serializing auth scheme <java.lang.ClassNotFoundException: org.apache.http.impl.auth.BasicScheme>java.lang.ClassNotFoundException: org.apache.http.impl.auth.BasicScheme
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:71)
        at java.lang.Class.forName(DynamicHub.java:1319)
        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:759)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1872)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2179)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453)
        at org.apache.http.impl.client.BasicAuthCache.get(BasicAuthCache.java:130)
        at org.apache.http.client.protocol.RequestAuthCache.process(RequestAuthCache.java:108)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.nio.client.MainClientExec.prepareRequest(MainClientExec.java:520)
        at org.apache.http.impl.nio.client.MainClientExec.prepare(MainClientExec.java:146)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:128)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:271)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1628)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1568)
        at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:533)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendRecords(ElasticsearchLogWriter.kt:129)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendNextBatch(ElasticsearchLogWriter.kt:109)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendData(ElasticsearchLogWriter.kt:94)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter$workerThread$1.invoke(ElasticsearchLogWriter.kt:64)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter$workerThread$1.invoke(ElasticsearchLogWriter.kt:63)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
`
I've tried register BasicAuthCache class for reflection

`@RegisterForReflection(targets = {
        BasicAuthCache.class
})`

but after that I receive another problem ...

`[WARN] BasicAuthCache - Unexpected I/O error while de-serializing auth scheme <java.io.InvalidClassException: org.apache.http.impl.auth.BasicScheme; no valid constructor>java.io.InvalidClassException: org.apache.http.impl.auth.BasicScheme; no valid constructor
        at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:173)
        at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2180)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453)
        at org.apache.http.impl.client.BasicAuthCache.get(BasicAuthCache.java:130)
        at org.apache.http.client.protocol.RequestAuthCache.process(RequestAuthCache.java:108)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.nio.client.MainClientExec.prepareRequest(MainClientExec.java:520)
        at org.apache.http.impl.nio.client.MainClientExec.prepare(MainClientExec.java:146)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:128)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:271)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1628)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1568)
        at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:533)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendRecords(ElasticsearchLogWriter.kt:129)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendNextBatch(ElasticsearchLogWriter.kt:109)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendData(ElasticsearchLogWriter.kt:94)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter$workerThread$1.invoke(ElasticsearchLogWriter.kt:64)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter$workerThread$1.invoke(ElasticsearchLogWriter.kt:63)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

`

**Comment by codinux-gmbh** [comment]
Does it work when you run your application on the JVM, e.g. with
`./gradlew quarkusDev`

As i have no experience at all with Quarkus Native, we are running all our Quarkus services on the JVM.

Does it work when you also register `BasicScheme` (and may also its parent class `RFC2617Scheme`) for reflection?

**Comment by miramax777** [comment]
Thanks for your fast answer !

In dev mode everything works fine.

I've tried to register BasicScheme and RFC2617Scheme for reflection, but again receive same error when run built native image.

`[WARN] BasicAuthCache - Unexpected I/O error while de-serializing auth scheme <java.io.InvalidClassException: org.apache.http.impl.auth.BasicScheme; no valid constructor>java.io.InvalidClassException: org.apache.http.impl.auth.BasicScheme; no valid constructor
        at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:173)
        at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2180)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453)
        at org.apache.http.impl.client.BasicAuthCache.get(BasicAuthCache.java:130)
        at org.apache.http.client.protocol.RequestAuthCache.process(RequestAuthCache.java:108)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.nio.client.MainClientExec.prepareRequest(MainClientExec.java:520)
        at org.apache.http.impl.nio.client.MainClientExec.prepare(MainClientExec.java:146)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:128)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:271)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1628)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1568)
        at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:533)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendRecords(ElasticsearchLogWriter.kt:129)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendNextBatch(ElasticsearchLogWriter.kt:109)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter.sendData(ElasticsearchLogWriter.kt:94)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter$workerThread$1.invoke(ElasticsearchLogWriter.kt:64)
        at net.codinux.log.elasticsearch.ElasticsearchLogWriter$workerThread$1.invoke(ElasticsearchLogWriter.kt:63)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
`

**Comment by miramax777** [comment]
Hi guys.

Do you have any updates about this problem ? May be better to use more "quarkus friendly"  http client, like Web Client instead of Apache Http Client ?

**Comment by codinux-gmbh** [comment]
This is not by us -i personally dislike the Apache HttpClient - but Elasticsearch's RestHighLevelClient uses it internally.

There are plans to completely replace the RestHighLevelClient by e.g. OkHttp, but this will take some time.

Could you check to see how to use the Apache HttpClient in Quarkus Native? As i said i have no experience at all with Quarkus Native.

**Comment by t1** [comment]
We have the same issue, and we always run in JVM mode. It would be cool for us, if you'd publish a release and take a look at the native compilation issue in a second step?

**Comment by codinux-gmbh** [comment]
Sorry for the late response. Just released version `2.5.0` which enables to set username and password:
```
quarkus.log.elasticsearch.host=https://es-host:9200
quarkus.log.elasticsearch.username=user123
quarkus.log.elasticsearch.password=password123

# in case of self-signed certificates may disable certificate check by setting to true
quarkus.log.elasticsearch.disable-certificate-check=false
```

Using now the OpenSeachClient, so that ES 7, ES 8 and OpenSearch is supported. But as it uses Apache HttpClient as well, still don't think that it works in native mode, working on that.
